version: '3'
services:
  app:
    build: ./client/
    restart: always
    image: hell-display_app
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${NGINX_DOMAIN}
      LETSENCRYPT_HOST: ${NGINX_DOMAIN}
      LETSENCRYPT_EMAIL: ${NGINX_EMAIL}
    
  server:
    build: ./server/
    restart: always
    image: hell-display_server
    expose:
      - 4001
      - 5001
    volumes:
      - certs:/etc/nginx/certs:ro
    environment:
      API_HOST: ${NGINX_DOMAIN}
      API_PORTS: 4001,5001
      API_HTTPS: 4001,5001

networks:
    default:
        external:
            name: nginx-proxy

volumes:
  certs:
    external:
      name:  nginx-proxy_certs